In [1]:
import gower
import pandas as pd
import numpy as np
from sklearn.neighbors import DistanceMetric

In [2]:
df = pd.DataFrame([[1,2.6,'A'],[12,5,'X'],[4,7,'A']])
df.columns = ['Num_1','Num_2','Cat_1']
df

Num_1  Num_2 Cat_1
0      1    2.6     A
1     12    5.0     X
2      4    7.0     A

In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import DistanceMetric

In [4]:
s1 = DistanceMetric.get_metric('manhattan').pairwise(df[['Num_1']])
s1

array([[ 0., 11.,  3.],
       [11.,  0.,  8.],
       [ 3.,  8.,  0.]])

In [5]:
s1 = s1/max(np.ptp(df['Num_1']),1)
s1

array([[0.        , 1.        , 0.27272727],
       [1.        , 0.        , 0.72727273],
       [0.27272727, 0.72727273, 0.        ]])

In [6]:
s2 = DistanceMetric.get_metric('manhattan').pairwise(df[['Num_2']])/max(np.ptp(df['Num_2']),1)
s2

array([[0.        , 0.54545455, 1.        ],
       [0.54545455, 0.        , 0.45454545],
       [1.        , 0.45454545, 0.        ]])

In [7]:
f =  df.iloc[:,[2]]
dummy_df = pd.get_dummies(f)
dummy_df

Cat_1_A  Cat_1_X
0        1        0
1        0        1
2        1        0

In [8]:
s3 = DistanceMetric.get_metric('dice').pairwise(dummy_df)
s3

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

In [9]:
w1 = w2 = w3 = 1

In [10]:
Gowers_Distance = (s1*w1 + s2*w2 + s3*w3)/(w1 + w2 + w3) 
Gowers_Distance

array([[0.        , 0.84848485, 0.42424242],
       [0.84848485, 0.        , 0.72727273],
       [0.42424242, 0.72727273, 0.        ]])

### Writng a function for the above code

In [11]:
def gower_distance(X):
    individual_variable_distances = []

    for i in range(X.shape[1]):
        
        feature = X.iloc[:,[i]]
        if feature.dtypes.values == np.object:
            
            feature_dist = DistanceMetric.get_metric('dice').pairwise(pd.get_dummies(feature))
        else:
            
            feature_dist = DistanceMetric.get_metric('manhattan').pairwise(feature) / max(np.ptp(feature.values),1)

        individual_variable_distances.append(feature_dist)

    return np.array(individual_variable_distances).mean(0)

In [12]:
gower_distance(df)

array([[0.        , 0.84848485, 0.42424242],
       [0.84848485, 0.        , 0.72727273],
       [0.42424242, 0.72727273, 0.        ]])

In [13]:
import gower
gower.gower_matrix(df)

array([[0.        , 0.8484848 , 0.4242424 ],
       [0.8484848 , 0.        , 0.72727275],
       [0.4242424 , 0.72727275, 0.        ]], dtype=float32)